### ISSUE TITLE
Saran

### ISSUE THREAD

**Issue by freyandhy** [farridkun/challenge-javascript-ga-binar#1]
Halo Mas Farid (@farridkun ), thanks berat sudah menyelesaikan tugasnya 👍 

ada beberapa saran dari saya

- Dalam pembuatan function, sebaiknya nilai inputan menjadi parameter.
- Untuk looping genap. Jika inputan angka ganjil, perulangan tetap dilakukan dengan hanya menampilkan bilangan yang genap. Contoh jika saya inputkan angka 15, maka menampilkan perulangan dari 0 s/d 14. Begitu pun sebaliknya untuk yang looping ganjil

keep practicing & explore :D

**Comment by farridkun** [comment]
> Halo Mas Farid (@farridkun ), thanks berat sudah menyelesaikan tugasnya 👍 
> 
> 
> 
> ada beberapa saran dari saya
> 
> 
> 
> - Dalam pembuatan function, sebaiknya nilai inputan menjadi parameter.
> 
> - Untuk looping genap. Jika inputan angka ganjil, perulangan tetap dilakukan dengan hanya menampilkan bilangan yang genap. Contoh jika saya inputkan angka 15, maka menampilkan perulangan dari 0 s/d 14. Begitu pun sebaliknya untuk yang looping ganjil
> 
> 
> 
> keep practicing & explore :D

Wah terima kasih banyak atas masukan dan sarannya mas frey ( @freyandhy  )akan jadi bahan perbaikan kedepannya bagi saya🙏🏻😀
